import Link from 'next/link'
import type { ClientStatus, DashboardDateRange } from '../types'

const statuses: Array<ClientStatus | 'All'> = ['All', 'Live', 'Draft', 'Invited', 'No profile']
const dateRanges: Array<{ label: string; days: DashboardDateRange }> = [{ label: 'Last 7 days', days: 7 }, { label: 'Last 14 days', days: 14 }, { label: 'Last 30 days', days: 30 }, { label: 'Last 90 days', days: 90 }]

export function AdminTopbar({ query, status, dateRange, onQueryChange, onStatusChange, onDateRangeChange }: { query: string; status: ClientStatus | 'All'; dateRange: DashboardDateRange; onQueryChange: (value: string) => void; onStatusChange: (value: ClientStatus | 'All') => void; onDateRangeChange: (value: DashboardDateRange) => void }) {
  return <div className="topbar-inner"><label className="global-search"><span aria-hidden="true">⌕</span><span className="sr-only">Search clients</span><input type="search" aria-label="Search clients" placeholder="Search clients by name, email, or segment..." value={query} onChange={(event) => onQueryChange(event.target.value)} /><kbd>⌘ K</kbd></label><div className="topbar-actions"><Link className="personal-dashboard-link" href="/dashboard">Your dashboard</Link><label className="utility-select"><span className="sr-only">Filter by status</span><select aria-label="Filter by status" value={status} onChange={(event) => onStatusChange(event.target.value as ClientStatus | 'All')}>{statuses.map((item) => <option key={item}>{item === 'All' ? 'All clients' : item}</option>)}</select></label><label className="utility-select date-range-select"><span className="sr-only">Date range</span><select aria-label="Date range" value={dateRange} onChange={(event) => onDateRangeChange(Number(event.target.value) as DashboardDateRange)}>{dateRanges.map((item) => <option key={item.days} value={item.days}>{item.label}</option>)}</select></label><button className="notification-button" type="button" aria-label="Notifications">♧</button><button className="account-control" type="button" aria-label="Admin account menu"><span className="account-avatar" aria-hidden="true">A</span><span className="account-details"><strong>Admin</strong><small>Admin account</small></span><span aria-hidden="true">⌄</span></button></div></div>
}
